#!/usr/bin/env python

# Test requirement for pygtk 2.0
import pygtk
pygtk.require("2.0")

from yomanlib.models.appmodel import AppModel
from yomanlib.controllers.appctl import AppCtl
from yomanlib.views.appview import AppView

model = AppModel()
view = AppView()
ctl = AppCtl(model, view)

import gtk
gtk.main()
